### ISSUE TITLE
[BUG] Creative duplication (Dont close for no reason)

### ISSUE THREAD

**Issue by UnEnanoMas** [HighTecDev/ArmorStandExpanded#11]
It can continue to be duplicated while in creative, the player still has the item in hand after placing it on the armor holder.

Dev: 17 #
Pocketmine: 3.15.4
Php: 7.3
Version: 1.16.40
Device: Windows 10, Android 10

**Comment by HighTecDev** [comment]
It is normal that its duplicate in CreativeMode. Please test it in SurvivalMode and dont open a new Issue while you can comment in the original Issue.

**Comment by HighTecDev** [comment]
And as a little Hint: in CreativeMode you can also duplicate Items with ItemFrames. That is what CreativeMode is used for

**Comment by HighTecDev** [comment]
@UnEnanoMas

**Comment by UnEnanoMas** [comment]
Yes, but the bad thing is having Economy on the server, and that people with high rank (which includes creative) can take advantage of it and clone everywhere

**Comment by UnEnanoMas** [comment]
I have my totally limited creative, they cannot open chests, or interact with anything, and now this is the only way they have found to duplicate

**Comment by UnEnanoMas** [comment]
@HighTecDev

**Comment by HighTecDev** [comment]
Its not Part of this Plugin to take Care of a DuplicationProtection for CreativeModes. Its add an Armorstand like it should work in Vanilla. 
If you want a Protection for that you have add it by yourself like you do with your Chests and so on

**Comment by UnEnanoMas** [comment]
I understand, thank you, I will not bother you anymore <3
