### ISSUE TITLE
Armor can be removed even with protection

### ISSUE THREAD

**Issue by UnEnanoMas** [HighTecDev/ArmorStandExpanded#13]
A player has just gone to Plots, and has shot a bow enchanted with Flame at an armor rack and after 3-4 shots, he has managed to knock it down and it has been destroyed

**Comment by UnEnanoMas** [comment]
And if u are in /gamemode 3, u can hit the armor, and its broken

**Comment by HighTecDev** [comment]
Thanks, i will have a look at this

**Comment by HighTecDev** [comment]
@UnEnanoMas Please try the latest Build now ;-)
