### ISSUE TITLE
item dupe

### ISSUE THREAD

**Issue by Aiawaska** [HighTecDev/ArmorStandExpanded#14]
players have figured out how to dupe

**Comment by HighTecDev** [comment]
I cant do anything with this Description.
Please explain how the Player Dupe with the Armorstand
@Aiawaska

**Comment by galaxytwenty** [comment]
I Think Aiawaska means, the same like me.

when hit the Armorstand with the hand Drop´s one Armorstands
when hit the Armorstand with a Sword drop two Armorstands

so one Armorstand makes two and two four, and so on 

Best Greeetz
