### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by UnEnanoMas** [HighTecDev/ArmorStandExpanded#15]
If you are in spectator mode (gamemode 3) and you quickly shift and touch an armor stand, the armor stand changes shape

https://user-images.githubusercontent.com/63286108/103635476-daade080-4f48-11eb-8296-b777624abe51.mp4

It's not a big deal, but I don't think it should interact xd

**Comment by HighTecDev** [comment]
XD
Ok thanks for the Report. I will have a look at this.
