### ISSUE TITLE
when i hit the stand with a sword...

### ISSUE THREAD

**Issue by galaxytwenty** [HighTecDev/ArmorStandExpanded#16]
hey lil bug.
when i hit the stand with a sword, then drops 2 stands.
can u fix ?.

THX 
Best Regardz

**Comment by HighTecDev** [comment]
I will have a look the next days

**Comment by galaxytwenty** [comment]
best THX 
Players Dupliate The stands :(
so i must Deactivate This very Great Plugin :(

**Comment by galaxytwenty** [comment]
I'm not sure if you could fix that, but the armor stands are stacked by BurgerSpawner.

I would like to prevent this. I would be happy if you would manage that too :) :)

**Comment by galaxytwenty** [comment]
I just noticed that everything that is on the stand is simply doubled

**Comment by galaxytwenty** [comment]
in the V1.1 works, but no with burgerspawner :)

**Comment by HighTecDev** [comment]
I've been looking into it now. That ArmorStand and content is double dropped only happens when the Damageris in CreativeMode. In SurviavalMode this error does not exist. 
Can you confirm that?
@galaxytwenty

**Comment by galaxytwenty** [comment]
I use burgerspawner so that the stand stacks and of course the items drop twice.

without burgerspawner can i confirm.
I'm stupid that I didn't pay attention to it...

can you maybe help with burgerspawner and prevent the stacking of the armor stands? 

Best THX. and Best THX for This AWESOME Plugin

**Comment by HighTecDev** [comment]
In addition, I just don’t understand what you mean with Armor Stand is stacked from BurgerSpawners. 
Please contact me best via DC

HighTec#7159

**Comment by galaxytwenty** [comment]
sry for my englisch :( have add you in DC

**Comment by HighTecDev** [comment]
Apart from that, I now release a commit against doubling in CreativeMode. I’d be happy if you would test this before.

**Comment by galaxytwenty** [comment]
sure, very much even

**Comment by galaxytwenty** [comment]
can you confirm, my request in DC

**Comment by galaxytwenty** [comment]
than you can close Here and Thanks for Support :)

**Comment by HighTecDev** [comment]
fixed
