### ISSUE TITLE
Duplicating 

### ISSUE THREAD

**Issue by xKurt** [HighTecDev/ArmorStandExpanded#20]
Players can duplicates stuff.
I dont know how but they can. Maybe because of the BurgerSpawners, or PiggyCustomEnchants.
They can duplicate everything when the Armor Stand is stacked.
I am using the latest version of PMMP and the Plugin.

**Comment by HighTecDev** [comment]
The Armorstand itself have no Duplication Bugs. The Issue with BurgerSpawners is nothing what i can fix in Armorstand.
A few month ago i have created a PullRequest to BurgerSpawners what should fix it. This PR was merged but i dont know if the Developer gas released this fix to poggit. Please contact the Developer from Burgerspawner.
@xKurt

**Comment by HighTecDev** [comment]
@xKurt 
This Bug was fixed in Burgerspawner with this commit:
https://github.com/Heisenburger69/BurgerSpawners/commit/278c0b1ff21c44c7400daa01e8ff1b0e655ce43d

Just use the latest DevBuild

**Comment by xKurt** [comment]
Alr thanks a lot!
