### ISSUE TITLE
Duplication Bug with TableSpoon and ArmorstandExpandet

### ISSUE THREAD

**Issue by Lesauw** [HighTecDev/ArmorStandExpanded#23]
When using TableSpoon or TeaSpoon and ArmorstandExpandet, if the Armorstand is holding an item and long press again to put an item in the hand, the item will multiply.

**Comment by Lesauw** [comment]
I additionally use Altay vll it is also because of that don't know if they fix Altay bugs

**Comment by HighTecDev** [comment]
@Lesauw  A DuplicationBug with TableSpoon in this case is not know yet.
ArmorStandExpanded is made for Pocketmine and not for Altay.
As far as i know, Altay have implemented his own ArmorStand, so ArmorStandExpanded isnt needed there.
