### ISSUE TITLE
Sorry for Next Issue

### ISSUE THREAD

**Issue by MonoAdrian23** [HighTecDev/ArmorStandExpanded#4]
Since latest Update of ArmorStands we cant hit head and slapper entities.
ArmorStands Dev 11 
Pocketmine 3.15.2
Used Plugins are Slapper and CB-Heads

**Comment by HighTecDev** [comment]
Head and SlapperEntities are not mentioned anywhere in this Plugin

**Comment by MonoAdrian23** [comment]
Hm OK
Then i must uninstall this Plugin.
But thanks for it 😕

**Comment by MonoAdrian23** [comment]
For Last
Mobs, Entities Not damagable
