### ISSUE TITLE
Wtf is this Shit?

### ISSUE THREAD

**Issue by MonoAdrian23** [HighTecDev/ArmorStandExpanded#5]
This Plugin destroys all Server logics.
We cant hit Mobs, Heads and another Entities!
And this Plugin is released?
Blame Dev, Blame Jasonwynn.

**Comment by HighTecDev** [comment]
Its tested. You are the only one who have this kind of shit. Go check it

**Comment by HighTecDev** [comment]
@MonoAdrian23 
Please try the lates Build now.
This Issue should be fixed.
