### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by LlamaDev92** [HighTecDev/ArmorStandExpanded#6]
I have install this Plugin but other Mobs and Entities are not damagable.
Pureentitiesx doenst Work, Heads and much more Entity Plugins Not useable.
How to fix?
Because this is very important for Servers.

**Comment by HighTecDev** [comment]
I look after it tomorrow

**Comment by HighTecDev** [comment]
Can you tell me you PM-Version and your Plugins?

**Comment by HighTecDev** [comment]
@LlamaDev92 
Please try the latest Build now. This Issue should be fixed
