### ISSUE TITLE
myplot nicht protectet 

### ISSUE THREAD

**Issue by efor89** [HighTecDev/ArmorStandExpanded#9]
hi
der ständer an sich kann nicht abgebaut werden aber die items können von jedem genommen werden!

lg efor89

**Comment by HighTecDev** [comment]
Ich teste es nachher gerne noch einmal aber genau das hatte ich eigentlich geschützt.

**Comment by HighTecDev** [comment]
@efor89 
Ich habe es jetzt nochmal getestet. Bei mir besteht dieses Problem nicht.
Nutzt du das neuste Build?

**Comment by efor89** [comment]
ich nutz das aktuele armorstand pl und myplot 1.7.1

**Comment by efor89** [comment]
ich nutz das ganze auf altay eventuel liegt es dadran

**Comment by efor89** [comment]
wäre echt nice wenn das funktionieren würde auf altay da der armorstand da überhaupt kein schutz hat

**Comment by HighTecDev** [comment]
Das Plugin ist aktuell nur auf PocketMine selbst ausgelegt.
Altay hat, soweit ich weiss, seinen eigenen Rüstungsständer bereits integriert. 
Ich schließe dieses Issue ersteinmal. Vielleicht werde ich bei Gelegenheit mal einen Altay-Fork anlegen.
Ich danke dir für dein Feedback.

**Comment by efor89** [comment]
jo dadrüber würde ich mich mega freuen versuch schon seit wochen jmd zu finden der mir ein plugin dafür schreibt das der armorstand ein myplot schutz bekommt

**Comment by HighTecDev** [comment]
Wenn du den Rest selbst hinbekommst kannst du aber gerne die canDoThis()-Methode dieses Plugins benutzen. Diese überprüft die Plotberechtigung
@efor89

**Comment by efor89** [comment]
aber zumindest kann der armorstand an sich schon ma nicht mehr abgebaut werden ^^
